version: '3.1'

services:
    relayer:
        container_name: hermes-${TAG:-1.2.0}
        command: /bin/bash
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - TAG=${TAG:-1.2.0}
        volumes:
            - ./init:/home/hermes/init
            - ./home:/home/hermes/.hermes
        environment:
            - CHAIN_ID_A=${CHAIN_ID_A:-testnet-1}
            - CHAIN_ID_B=${CHAIN_ID_B:-testnet-2}
            - RPC_ADDR_A=${RPC_ADDR_A:-http://rpc-testnet-1.com:26657}
            - RPC_ADDR_B=${RPC_ADDR_B:-http://rpc-testnet-2.com:26657}
            - GRPC_ADDR_A=${GRPC_ADDR_A:-http://grpc-testnet-1.com:9090}
            - GRPC_ADDR_B=${GRPC_ADDR_B:-http://grpc-testnet-2.com:9090}
            - WEBSOCK_ADDR_A=${WEBSOCK_ADDR_A:-ws://ws-testnet-1.com:1317/websocket}
            - WEBSOCK_ADDR_B=${WEBSOCK_ADDR_B:-ws://ws-testnet-2.com:1317/websocket}
            - COINTYPE_A=${COINTYPE_A:-330}
            - COINTYPE_B=${COINTYPE_B:-330}
            - PREFIX_A=${PREFIX_A:-terra}
            - PREFIX_B=${PREFIX_B:-terra}
        extra_hosts:
            - "host.docker.internal:host-gateway"
